# Generated by Django 3.2.9 on 2023-12-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('data_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorWiseReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.CharField(max_length=20)),
                ('data_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IPDDeposit',
            fields=[
                ('deposit_id', models.AutoField(primary_key=True, serialize=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IPDDischarge',
            fields=[
                ('discharge_id', models.AutoField(primary_key=True, serialize=False)),
                ('discharge_date', models.DateField()),
                ('discharge_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TPAReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('tpa_id', models.CharField(max_length=20)),
                ('transaction_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WardWiseReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('ward', models.CharField(max_length=50)),
                ('data_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IPDRegistration',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_date', models.DateField()),
                ('ward', models.CharField(max_length=50)),
                ('bed_number', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='IPDDischargeReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_details', models.TextField()),
                ('discharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ipddischarge')),
            ],
        ),
        migrations.AddField(
            model_name='ipddischarge',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ipdregistration'),
        ),
        migrations.CreateModel(
            name='IPDDepositReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_details', models.TextField()),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ipddeposit')),
            ],
        ),
        migrations.AddField(
            model_name='ipddeposit',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ipdregistration'),
        ),
        migrations.CreateModel(
            name='IPDAdmitReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_details', models.TextField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ipdregistration')),
            ],
        ),
    ]
