# Generated by Django 4.1.13 on 2023-12-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_age_patient_broughtby_patient_careofperson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='City',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Taluka',
        ),
        migrations.AddField(
            model_name='patient',
            name='CityTaluka',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ModeOfArrival',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='RelationWithPatient',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Sibling', 'Sibling'), ('Spouse', 'Spouse'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Religion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='State',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
