# Generated by Django 4.1.13 on 2023-12-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_age_remove_patient_broughtby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
