# Generated by Django 4.1.13 on 2024-01-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('specialty', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Address', models.TextField()),
                ('PinCode', models.CharField(blank=True, max_length=10, null=True)),
                ('experince', models.CharField(max_length=100)),
                ('education_qualification', models.CharField(max_length=100)),
                ('working_details', models.CharField(max_length=100)),
                ('identity_proof', models.ImageField(upload_to='identity_proofs/')),
                ('medical_liscence', models.ImageField(upload_to='medical_licenses/')),
            ],
        ),
    ]
